const birds = {
    "alouette_champs": "Alouette des champs",
    "alouette_lulu": "Alouette lulu",
    "buse": "Buse",
    "chardonneret_elegant": "Chardonneret élegant",
    "chouette_hulotte": "Chouette hulotte",
    "corneille": "Corneille",
    "coucou": "Coucou",
    "faucon_crecerelle": "Faucon crecerelle",
    "fauvette_jardins": "Fauvette des jardins",
    "fauvette_tete_noire": "Fauvette à tête noire",
    "geai_des_chenes": "Geai des Chênes",
    "goeland": "Goëland",
    "grand_corbeau": "Grand corbeau",
    "grive_draine": "Grive draine",
    "grive_musicienne": "Grive musicienne",
    "merle_noir": "Merle noir",
    "mesange_bleue": "Mésange bleue",
    "mesange_charbonniere": "Mésange charbonnière",
    "mesange_noire": "Mésange noire",
    "pic_noir": "Pic noir",
    "pic_vert": "Pic vert",
    "pigeon_ramier": "Pigeon ramier",
    "pinson_des_arbres": "Pinson des arbres",
    "pouillot_veloce": "Pouillot Véloce",
    "rougegorge_familier": "Rouge-gorge familier",
    "tourterelle": "Tourterelle",
    "troglodyte_mignon": "Troglodyte mignon"
};

const birds_v2 = {
    "_template": {
        identity: {
            commonName: "",
            latinName: "",
            order: "",
            family: "",
            genre: "",
        },
        externalSource: [
            {
                id: "",
                source: "",
                author: "",
                authorURL: "",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },
            {
                id: "",
                source: "",
                author: "",
                authorURL: "",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },
        ]
    },
    "alouette_champs": {
        identity: {
            commonName: "Alouette des champs",
            latinName: "Alauda arvensis",
            order: "Passeriformes",
            family: "Alaudidae",
            genre: "Alauda",
        },
        externalSource: [
            {
                id: "XC319328",
                source: "https://www.xeno-canto.org/319328",
                author: "david m",
                authorURL: "https://www.xeno-canto.org/contributor/BTOFEKXFGW",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },
            {
                id: "XC555189",
                source: "https://www.xeno-canto.org/555189",
                author: "Guillaume Bigayon",
                authorURL: "https://www.xeno-canto.org/contributor/HCKTRQCLWR",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            }
        ],
    },
    "alouette_lulu": {
        identity: {
            commonName: "Alouette lulu",
            latinName: "Lullula arborea",
            order: "Passeriformes",
            family: "Alaudidae",
            genre: "Lullula",
        },
        externalSource: [
            {
                id: "XC357096",
                source: "https://www.xeno-canto.org/357096",
                author: "Alexandre Moreira",
                authorURL: "https://www.xeno-canto.org/contributor/ZVWHOCJNMO",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },
            {
                id: "XC534237",
                source: "https://www.xeno-canto.org/534237",
                author: "Mark Smiles",
                authorURL: "https://www.xeno-canto.org/contributor/BRNDUHWRLE",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },

        ]
    },
    "buse_variable": {
        identity: {
            commonName: "Buse variable",
            latinName: "Buteo buteo",
            order: "Accipitriformes",
            family: "Accipitridae",
            genre: "Buteo",
        },
        externalSource: [
            {
                id: "XC419545",
                source: "https://www.xeno-canto.org/419545",
                author: "Jorge Leitão",
                authorURL: "https://www.xeno-canto.org/contributor/GYAUIPUVNM",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },
            {
                id: "XC638480",
                source: "https://www.xeno-canto.org/638480",
                author: "Stanislas Wroza",
                authorURL: "https://www.xeno-canto.org/contributor/SDPCHKOHRH",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },
            {
                id: "XC623609",
                source: "https://www.xeno-canto.org/623609",
                author: "Frank Lambert",
                authorURL: "https://www.xeno-canto.org/contributor/YTUXOCTUEM",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },

        ]
    },
    "chardonneret_elegant": {
        identity: {
            commonName: "Chardonneret élegant",
            latinName: "Carduelis carduelis",
            order: "Passeriformes",
            family: "Fringillidae",
            genre: "Carduelis",
        },
        externalSource: [
            {
                id: "XC194581",
                source: "https://www.xeno-canto.org/194581",
                author: "Albert Lastukhin",
                authorURL: "https://www.xeno-canto.org/contributor/LELYWQKUZX",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },
            {
                id: "XC375574",
                source: "https://www.xeno-canto.org/375574",
                author: "Roby",
                authorURL: "https://www.xeno-canto.org/contributor/KDUPOCIDHM",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },

        ]
    },
    "chouette_hulotte": {
        identity: {
            commonName: "Chouette hulotte",
            latinName: "Strix aluco",
            order: "Strigiformes",
            family: "Strigidae",
            genre: "Strix",
        },
        externalSource: [
            {
                id: "XC619027 ",
                source: "https://www.xeno-canto.org/619027",
                author: "Cedric Mroczko",
                authorURL: "https://www.xeno-canto.org/contributor/TJSRKPHQNP",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },
            {
                id: "XC485627",
                source: "https://www.xeno-canto.org/485627",
                author: "Grzegorz Lorek",
                authorURL: "https://www.xeno-canto.org/contributor/JXZFXAZWHY",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },
            {
                id: "XC619301 ",
                source: "https://www.xeno-canto.org/619301",
                author: "Jean-François Azens",
                authorURL: "https://www.xeno-canto.org/contributor/DUUYLLTNQS",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },
        ]
    },
    "corneille_noire": {
        identity: {
            commonName: "Corneille noire",
            latinName: "Corvus corone",
            order: "Passeriformes",
            family: "Corvidae",
            genre: "Corvus",
        },
        externalSource: [
            {
                id: "XC457702",
                source: "https://www.xeno-canto.org/457702",
                author: "Louis A. Hansen",
                authorURL: "https://www.xeno-canto.org/contributor/SGNUEQHVBW",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },
            {
                id: "XC380326",
                source: "https://www.xeno-canto.org/380326",
                author: "Cedric Mroczko",
                authorURL: "https://www.xeno-canto.org/contributor/TJSRKPHQNP",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },
            {
                id: "XC491193",
                source: "https://www.xeno-canto.org/491193",
                author: "Marie-Lan Taÿ Pamart",
                authorURL: "https://www.xeno-canto.org/contributor/CGRIFXISGE",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },
            {
                id: "XC183098",
                source: "https://www.xeno-canto.org/183098",
                author: "Albert Lastukhin",
                authorURL: "https://www.xeno-canto.org/contributor/LELYWQKUZX",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },
            {
                id: "XC586541",
                source: "https://www.xeno-canto.org/586541",
                author: "Ad Hilders",
                authorURL: "https://www.xeno-canto.org/contributor/UBDTVCWYPJ",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },
        ]
    },
    "coucou_gris": {
        identity: {
            commonName: "Coucou gris",
            latinName: "Cuculus canorus",
            order: "Cuculiformes",
            family: "Cuculidae",
            genre: "Cuculus",
        },
        externalSource: [
            {
                id: "XC552815",
                source: "https://www.xeno-canto.org/552815",
                author: "Ruud van Beusekom",
                authorURL: "https://www.xeno-canto.org/contributor/PKWMZIRVUO",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },
            {
                id: "XC26583",
                source: "https://www.xeno-canto.org/26583",
                author: "Bram Piot",
                authorURL: "https://www.xeno-canto.org/contributor/RGSEIIJGHA",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },
            {
                id: "XC480216",
                source: "https://www.xeno-canto.org/480216",
                author: "Albert Lastukhin",
                authorURL: "https://www.xeno-canto.org/contributor/LELYWQKUZX",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },
        ]
    },
    "faucon_crecerelle": {
        identity: {
            commonName: "Faucon crecerelle",
            latinName: "Falco tinnunculus",
            order: "Falconiformes",
            family: "Falconidae",
            genre: "Falco",
        },
        externalSource: [
            {
                id: "XC608710",
                source: "https://www.xeno-canto.org/608710",
                author: "Jarek Matusiak",
                authorURL: "https://www.xeno-canto.org/contributor/ZNCDXTUOFL",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },
            {
                id: "XC526971",
                source: "https://www.xeno-canto.org/526971",
                author: "Stanislas Wroza",
                authorURL: "https://www.xeno-canto.org/contributor/SDPCHKOHRH",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },
            {
                id: "XC595779",
                source: "https://www.xeno-canto.org/595779",
                author: "CLAES Victor",
                authorURL: "https://www.xeno-canto.org/contributor/URIFNYGGHK",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },
        ]
    },
    "fauvette_jardins": {
        identity: {
            commonName: "Fauvette des jardins",
            latinName: "Sylvia borin",
            order: "Passeriformes",
            family: "Sylviidae",
            genre: "Sylvia",
        },
        externalSource: [
            {
                id: "XC342327",
                source: "https://www.xeno-canto.org/342327",
                author: "Albert Lastukhin",
                authorURL: "https://www.xeno-canto.org/contributor/LELYWQKUZX",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },
            {
                id: "XC25698",
                source: "https://www.xeno-canto.org/25698",
                author: "Niels Krabbe",
                authorURL: "https://www.xeno-canto.org/contributor/XTVEPHMPPJ",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },
        ]
    },
    "fauvette_tete_noire": {
        identity: {
            commonName: "Fauvette à tête noire",
            latinName: "Sylvia atricapilla",
            order: "Passeriformes",
            family: "Sylviidae",
            genre: "Sylvia",
        },
        externalSource: [
            {
                id: "XC347322",
                source: "https://www.xeno-canto.org/347322",
                author: "Hugo Samain",
                authorURL: "https://www.xeno-canto.org/contributor/VECXKQXEZZ",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },
            {
                id: "XC548674",
                source: "https://www.xeno-canto.org/548674",
                author: "Mebarki",
                authorURL: "https://www.xeno-canto.org/contributor/KLOPJDTDWR",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },
            {
                id: "XC459023",
                source: "https://www.xeno-canto.org/459023",
                author: "BOUCHAREL Dominique",
                authorURL: "https://www.xeno-canto.org/contributor/YDVJBAWGXR",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },
            {
                id: "XC579964",
                source: "https://www.xeno-canto.org/579964",
                author: "Albert Lastukhin",
                authorURL: "https://www.xeno-canto.org/contributor/LELYWQKUZX",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },
        ]
    },
    "geai_des_chenes": {
        identity: {
            commonName: "Geai des Chênes",
            latinName: "Garrulus glandarius",
            order: "Passeriformes",
            family: "Corvidae",
            genre: "Garrulus",
        },
        externalSource: [
            {
                id: "XC377164",
                source: "https://www.xeno-canto.org/377164",
                author: "Gary Harbour",
                authorURL: "https://www.xeno-canto.org/contributor/HFRPNOEVFC",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },
            {
                id: "XC67320",
                source: "https://www.xeno-canto.org/67320",
                author: "Jan-Kees Bossenbroek",
                authorURL: "https://www.xeno-canto.org/contributor/DWZFTPIRLT",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },
            {
                id: "XC585680",
                source: "https://www.xeno-canto.org/585680",
                author: "Frank Holzapfel",
                authorURL: "https://www.xeno-canto.org/contributor/NKZQLCJFUU",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },
            {
                id: "XC628119",
                source: "https://www.xeno-canto.org/628119",
                author: "Jelle Scharringa",
                authorURL: "https://www.xeno-canto.org/contributor/KDTMIWOGNC",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },
        ]
    },
    "goeland_argente": {
        identity: {
            commonName: "Goéland argenté",
            latinName: "Larus argentatus",
            order: "Charadriiformes",
            family: "Laridae",
            genre: "Larus",
        },
        externalSource: [
            {
                id: "XC603672",
                source: "https://www.xeno-canto.org/603672",
                author: "Micha Luhn",
                authorURL: "https://www.xeno-canto.org/contributor/YSPYKACHLO",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },
            {
                id: "XC330973",
                source: "https://www.xeno-canto.org/330973",
                author: "Sylvan Schnabel",
                authorURL: "https://www.xeno-canto.org/contributor/PBXPSXGKLL",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },
            {
                id: "XC263926",
                source: "https://www.xeno-canto.org/263926",
                author: "Terje Kolaas",
                authorURL: "https://www.xeno-canto.org/contributor/CIMGCGUWCS",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },
            {
                id: "XC550608",
                source: "https://www.xeno-canto.org/550608",
                author: "B Whyte",
                authorURL: "https://www.xeno-canto.org/contributor/RWLOMPENJC",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },
            {
                id: "XC224818",
                source: "https://www.xeno-canto.org/224818",
                author: "Peter Boesman",
                authorURL: "https://www.xeno-canto.org/contributor/OOECIWCSWV",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },
            {
                id: "XC381818",
                source: "https://www.xeno-canto.org/381818",
                author: "Uku Paal",
                authorURL: "https://www.xeno-canto.org/contributor/XIBLXHRPJO",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },
        ]
    },
    "goeland_leucophee": {
        identity: {
            commonName: "Goéland leucophée",
            latinName: "Larus michahellis",
            order: "Charadriiformes",
            family: "Laridae",
            genre: "Larus",
        },
        externalSource: [
            {
                id: "XC285382",
                source: "https://www.xeno-canto.org/285382",
                author: "Cedric Mroczko",
                authorURL: "https://www.xeno-canto.org/contributor/TJSRKPHQNP",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },
            {
                id: "XC598877",
                source: "https://www.xeno-canto.org/598877",
                author: "Cedric Mroczko",
                authorURL: "https://www.xeno-canto.org/contributor/TJSRKPHQNP",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },
            {
                id: "XC378210",
                source: "https://www.xeno-canto.org/378210",
                author: "Pascal Christe",
                authorURL: "https://www.xeno-canto.org/contributor/SEIQHUBHAF",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },
            {
                id: "XC566661",
                source: "https://www.xeno-canto.org/566661",
                author: "Marcel Gil Velasco",
                authorURL: "https://www.xeno-canto.org/contributor/METIPYBSWG",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },
            {
                id: "XC460320",
                source: "https://www.xeno-canto.org/460320",
                author: "Nelson Conceição",
                authorURL: "https://www.xeno-canto.org/contributor/JYPQCEFKAM",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },
        ]
    },
    "grand_corbeau": {
        identity: {
            commonName: "Grand corbeau",
            latinName: "Corvus corax",
            order: "Passeriformes",
            family: "Corvidae",
            genre: "Corvus",
        },
        externalSource: [
            {
                id: "XC167827",
                source: "https://www.xeno-canto.org/167827",
                author: "Bodo Sonnenburg",
                authorURL: "https://www.xeno-canto.org/contributor/QAJPWEPSTL",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },
            {
                id: "XC357753",
                source: "https://www.xeno-canto.org/357753",
                author: "Jerome Fischer",
                authorURL: "https://www.xeno-canto.org/contributor/JPBSNBUUEF",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },
            {
                id: "XC72115",
                source: "https://www.xeno-canto.org/72115",
                author: "Richard E. Webster",
                authorURL: "https://www.xeno-canto.org/contributor/KZYUWIRZVH",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },
            {
                id: "XC334273",
                source: "https://www.xeno-canto.org/334273",
                author: "Yoann Blanchon",
                authorURL: "https://www.xeno-canto.org/contributor/OYXLQBTHRH",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },
        ]
    },
    "grive_draine": {
        identity: {
            commonName: "Grive draine",
            latinName: "Turdus viscivorus",
            order: "Passeriformes",
            family: "Turdidae",
            genre: "Turdus",
        },
        externalSource: [
            {
                id: "XC567093",
                source: "https://www.xeno-canto.org/567093",
                author: "Guillaume Bigayon",
                authorURL: "https://www.xeno-canto.org/contributor/HCKTRQCLWR",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },
            {
                id: "XC179931",
                source: "https://www.xeno-canto.org/179931",
                author: "Anthony McGeehan",
                authorURL: "https://www.xeno-canto.org/contributor/TYEQKORVXJ",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },
        ]
    },
    "grive_musicienne": "Grive musicienne",
    "merle_noir": "Merle noir",
    "mesange_bleue": "Mésange bleue",
    "mesange_charbonniere": "Mésange charbonnière",
    "mesange_noire": "Mésange noire",
    "pic_noir": "Pic noir",
    "pic_vert": "Pic vert",
    "pigeon_ramier": "Pigeon ramier",
    "pinson_des_arbres": "Pinson des arbres",
    "pouillot_veloce": {
        identity: {
            commonName: "Pouillot véloce",
            latinName: "Phylloscopus collybita",
            order: "Passeriformes",
            family: "Phylloscopidae",
            genre: "Phylloscopus",
        },
        externalSource: [
            {
                id: "XC468776",
                source: "https://www.xeno-canto.org/468776",
                author: "Lars Edenius",
                authorURL: "https://www.xeno-canto.org/contributor/MMEJYLOPDO",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },
            {
                id: "XC535498",
                source: "https://www.xeno-canto.org/535498",
                author: "Stanislas Wroza",
                authorURL: "https://www.xeno-canto.org/contributor/SDPCHKOHRH",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },
            {
                id: "XC480519",
                source: "https://www.xeno-canto.org/480519",
                author: "Albert Lastukhin",
                authorURL: "https://www.xeno-canto.org/contributor/LELYWQKUZX",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },
            {
                id: "XC480522",
                source: "https://www.xeno-canto.org/480522",
                author: "Albert Lastukhin",
                authorURL: "https://www.xeno-canto.org/contributor/LELYWQKUZX",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },
            {
                id: "XC480526",
                source: "https://www.xeno-canto.org/480526",
                author: "Albert Lastukhin",
                authorURL: "https://www.xeno-canto.org/contributor/LELYWQKUZX",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },
        ]
    },
    "rougegorge_familier": "Rouge-gorge familier",
    "tourterelle": "Tourterelle",
    "troglodyte_mignon": {
        identity: {
            commonName: "Troglodyte mignon",
            latinName: "Troglodytes troglodytes",
            order: "Passeriformes",
            family: "Troglodytidae",
            genre: "Troglodytes",
        },
        externalSource: [
            {
                id: "XC507551",
                source: "https://www.xeno-canto.org/507551",
                author: "Grzegorz Kaczorowski",
                authorURL: "https://www.xeno-canto.org/contributor/HRHQNZTQAN",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },
            {
                id: "XC534091",
                source: "https://www.xeno-canto.org/534091",
                author: "Sue Riffe",
                authorURL: "https://www.xeno-canto.org/contributor/PVQOLRXXWL",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },
            {
                id: "XC129254",
                source: "https://www.xeno-canto.org/129254",
                author: "Kerem Ali Boyla",
                authorURL: "https://www.xeno-canto.org/contributor/NEMUAOWFZM",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },
            {
                id: "XC555640",
                source: "https://www.xeno-canto.org/555640",
                author: "Harald Knödler",
                authorURL: "https://www.xeno-canto.org/contributor/TLYFJKFXUH",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },
            {
                id: "XC549118",
                source: "https://www.xeno-canto.org/549118",
                author: "Ad Hilders",
                authorURL: "https://www.xeno-canto.org/contributor/UBDTVCWYPJ",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },
        ]
    },
};

export { birds };