const birds = {
    "alouette_champs": "Alouette des champs",
    "alouette_lulu": "Alouette lulu",
    "buse": "Buse",
    "chardonneret_elegant": "Chardonneret élegant",
    "chouette_hulotte": "Chouette hulotte",
    "corneille": "Corneille",
    "coucou": "Coucou",
    "faucon_crecerelle": "Faucon crecerelle",
    "fauvette_jardins": "Fauvette des jardins",
    "fauvette_tete_noire": "Fauvette à tête noire",
    "geai_des_chenes": "Geai des Chênes",
    "goeland": "Goëland",
    "grand_corbeau": "Grand corbeau",
    "grive_draine": "Grive draine",
    "grive_musicienne": "Grive musicienne",
    "merle_noir": "Merle noir",
    "mesange_bleue": "Mésange bleue",
    "mesange_charbonniere": "Mésange charbonnière",
    "mesange_noire": "Mésange noire",
    "pic_noir": "Pic noir",
    "pic_vert": "Pic vert",
    "pigeon_ramier": "Pigeon ramier",
    "pinson_des_arbres": "Pinson des arbres",
    "pouillot_veloce": "Pouillot Véloce",
    "rougegorge_familier": "Rouge-gorge familier",
    "tourterelle": "Tourterelle",
    "troglodyte_mignon": "Troglodyte mignon"
};

const birds_v2 = {
    "_template": {
        identity: {
            commonName: "",
            latinName: "",
            order: "",
            family: "",
            genre: "",
        },
        externalSource: [
            {
                id: "",
                source: "",
                author: "",
                authorURL: "",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },
            {
                id: "",
                source: "",
                author: "",
                authorURL: "",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },
        ]
    },
    "alouette_champs": {
        identity: {
            commonName: "Alouette des champs",
            latinName: "Alauda arvensis",
            order: "Passeriformes",
            family: "Alaudidae",
            genre: "Alauda",
        },
        externalSource: [
            {
                id: "XC319328",
                source: "https://www.xeno-canto.org/319328",
                author: "david m",
                authorURL: "https://www.xeno-canto.org/contributor/BTOFEKXFGW",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },
            {
                id: "XC555189",
                source: "https://www.xeno-canto.org/555189",
                author: "Guillaume Bigayon",
                authorURL: "https://www.xeno-canto.org/contributor/HCKTRQCLWR",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            }
        ],
    },
    "alouette_lulu": {
        identity: {
            commonName: "Alouette lulu",
            latinName: "Lullula arborea",
            order: "Passeriformes",
            family: "Alaudidae",
            genre: "Lullula",
        },
        externalSource: [
            {
                id: "XC357096",
                source: "https://www.xeno-canto.org/357096",
                author: "Alexandre Moreira",
                authorURL: "https://www.xeno-canto.org/contributor/ZVWHOCJNMO",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },
            {
                id: "XC534237",
                source: "https://www.xeno-canto.org/534237",
                author: "Mark Smiles",
                authorURL: "https://www.xeno-canto.org/contributor/BRNDUHWRLE",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },

        ]
    },
    "buse_variable": {
        identity: {
            commonName: "Buse variable",
            latinName: "Buteo buteo",
            order: "Accipitriformes",
            family: "Accipitridae",
            genre: "Buteo",
        },
        externalSource: [
            {
                id: "XC419545",
                source: "https://www.xeno-canto.org/419545",
                author: "Jorge Leitão",
                authorURL: "https://www.xeno-canto.org/contributor/GYAUIPUVNM",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },
            {
                id: "XC638480",
                source: "https://www.xeno-canto.org/638480",
                author: "Stanislas Wroza",
                authorURL: "https://www.xeno-canto.org/contributor/SDPCHKOHRH",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },
            {
                id: "XC623609",
                source: "https://www.xeno-canto.org/623609",
                author: "Frank Lambert",
                authorURL: "https://www.xeno-canto.org/contributor/YTUXOCTUEM",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },

        ]
    },
    "chardonneret_elegant": {
        identity: {
            commonName: "Chardonneret élegant",
            latinName: "Carduelis carduelis",
            order: "Passeriformes",
            family: "Fringillidae",
            genre: "Carduelis",
        },
        externalSource: [
            {
                id: "XC194581",
                source: "https://www.xeno-canto.org/194581",
                author: "Albert Lastukhin",
                authorURL: "https://www.xeno-canto.org/contributor/LELYWQKUZX",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },
            {
                id: "XC375574",
                source: "https://www.xeno-canto.org/375574",
                author: "Roby",
                authorURL: "https://www.xeno-canto.org/contributor/KDUPOCIDHM",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },

        ]
    },
    "chouette_hulotte": {
        identity: {
            commonName: "Chouette hulotte",
            latinName: "Strix aluco",
            order: "Strigiformes",
            family: "Strigidae",
            genre: "Strix",
        },
        externalSource: [
            {
                id: "XC619027 ",
                source: "https://www.xeno-canto.org/619027",
                author: "Cedric Mroczko",
                authorURL: "https://www.xeno-canto.org/contributor/TJSRKPHQNP",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },
            {
                id: "XC485627",
                source: "https://www.xeno-canto.org/485627",
                author: "Grzegorz Lorek",
                authorURL: "https://www.xeno-canto.org/contributor/JXZFXAZWHY",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },
            {
                id: "XC619301 ",
                source: "https://www.xeno-canto.org/619301",
                author: "Jean-François Azens",
                authorURL: "https://www.xeno-canto.org/contributor/DUUYLLTNQS",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },
        ]
    },
    "corneille_noire": {
        identity: {
            commonName: "Corneille noire",
            latinName: "Corvus corone",
            order: "Passeriformes",
            family: "Corvidae",
            genre: "Corvus",
        },
        externalSource: [
            {
                id: "XC457702",
                source: "https://www.xeno-canto.org/457702",
                author: "Louis A. Hansen",
                authorURL: "https://www.xeno-canto.org/contributor/SGNUEQHVBW",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },
            {
                id: "XC380326",
                source: "https://www.xeno-canto.org/380326",
                author: "Cedric Mroczko",
                authorURL: "https://www.xeno-canto.org/contributor/TJSRKPHQNP",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },
            {
                id: "XC491193",
                source: "https://www.xeno-canto.org/491193",
                author: "Marie-Lan Taÿ Pamart",
                authorURL: "https://www.xeno-canto.org/contributor/CGRIFXISGE",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },
            {
                id: "XC183098",
                source: "https://www.xeno-canto.org/183098",
                author: "Albert Lastukhin",
                authorURL: "https://www.xeno-canto.org/contributor/LELYWQKUZX",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },
            {
                id: "XC586541",
                source: "https://www.xeno-canto.org/586541",
                author: "Ad Hilders",
                authorURL: "https://www.xeno-canto.org/contributor/UBDTVCWYPJ",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },
        ]
    },
    "coucou_gris": {
        identity: {
            commonName: "Coucou gris",
            latinName: "Cuculus canorus",
            order: "Cuculiformes",
            family: "Cuculidae",
            genre: "Cuculus",
        },
        externalSource: [
            {
                id: "XC552815",
                source: "https://www.xeno-canto.org/552815",
                author: "Ruud van Beusekom",
                authorURL: "https://www.xeno-canto.org/contributor/PKWMZIRVUO",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },
            {
                id: "XC26583",
                source: "https://www.xeno-canto.org/26583",
                author: "Bram Piot",
                authorURL: "https://www.xeno-canto.org/contributor/RGSEIIJGHA",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },
            {
                id: "XC480216",
                source: "https://www.xeno-canto.org/480216",
                author: "Albert Lastukhin",
                authorURL: "https://www.xeno-canto.org/contributor/LELYWQKUZX",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },
        ]
    },
    "faucon_crecerelle": {
        identity: {
            commonName: "Faucon crecerelle",
            latinName: "Falco tinnunculus",
            order: "Falconiformes",
            family: "Falconidae",
            genre: "Falco",
        },
        externalSource: [
            {
                id: "XC608710",
                source: "https://www.xeno-canto.org/608710",
                author: "Jarek Matusiak",
                authorURL: "https://www.xeno-canto.org/contributor/ZNCDXTUOFL",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },
            {
                id: "XC526971",
                source: "https://www.xeno-canto.org/526971",
                author: "Stanislas Wroza",
                authorURL: "https://www.xeno-canto.org/contributor/SDPCHKOHRH",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },
            {
                id: "XC595779",
                source: "https://www.xeno-canto.org/595779",
                author: "CLAES Victor",
                authorURL: "https://www.xeno-canto.org/contributor/URIFNYGGHK",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },
        ]
    },
    "fauvette_jardins": {
        identity: {
            commonName: "Fauvette des jardins",
            latinName: "Sylvia borin",
            order: "Passeriformes",
            family: "Sylviidae",
            genre: "Sylvia",
        },
        externalSource: [
            {
                id: "XC342327",
                source: "https://www.xeno-canto.org/342327",
                author: "Albert Lastukhin",
                authorURL: "https://www.xeno-canto.org/contributor/LELYWQKUZX",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },
            {
                id: "XC25698",
                source: "https://www.xeno-canto.org/25698",
                author: "Niels Krabbe",
                authorURL: "https://www.xeno-canto.org/contributor/XTVEPHMPPJ",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },
        ]
    },
    "fauvette_tete_noire": {
        identity: {
            commonName: "Fauvette à tête noire",
            latinName: "Sylvia atricapilla",
            order: "Passeriformes",
            family: "Sylviidae",
            genre: "Sylvia",
        },
        externalSource: [
            {
                id: "XC347322",
                source: "https://www.xeno-canto.org/347322",
                author: "Hugo Samain",
                authorURL: "https://www.xeno-canto.org/contributor/VECXKQXEZZ",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },
            {
                id: "XC548674",
                source: "https://www.xeno-canto.org/548674",
                author: "Mebarki",
                authorURL: "https://www.xeno-canto.org/contributor/KLOPJDTDWR",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },
            {
                id: "XC459023",
                source: "https://www.xeno-canto.org/459023",
                author: "BOUCHAREL Dominique",
                authorURL: "https://www.xeno-canto.org/contributor/YDVJBAWGXR",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },
            {
                id: "XC579964",
                source: "https://www.xeno-canto.org/579964",
                author: "Albert Lastukhin",
                authorURL: "https://www.xeno-canto.org/contributor/LELYWQKUZX",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },
        ]
    },
    "geai_des_chenes": {
        identity: {
            commonName: "Geai des Chênes",
            latinName: "Garrulus glandarius",
            order: "Passeriformes",
            family: "Corvidae",
            genre: "Garrulus",
        },
        externalSource: [
            {
                id: "XC377164",
                source: "https://www.xeno-canto.org/377164",
                author: "Gary Harbour",
                authorURL: "https://www.xeno-canto.org/contributor/HFRPNOEVFC",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },
            {
                id: "XC67320",
                source: "https://www.xeno-canto.org/67320",
                author: "Jan-Kees Bossenbroek",
                authorURL: "https://www.xeno-canto.org/contributor/DWZFTPIRLT",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },
            {
                id: "XC585680",
                source: "https://www.xeno-canto.org/585680",
                author: "Frank Holzapfel",
                authorURL: "https://www.xeno-canto.org/contributor/NKZQLCJFUU",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },
            {
                id: "XC628119",
                source: "https://www.xeno-canto.org/628119",
                author: "Jelle Scharringa",
                authorURL: "https://www.xeno-canto.org/contributor/KDTMIWOGNC",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },
        ]
    },
    "goeland_argente": {
        identity: {
            commonName: "Goéland argenté",
            latinName: "Larus argentatus",
            order: "Charadriiformes",
            family: "Laridae",
            genre: "Larus",
        },
        externalSource: [
            {
                id: "XC603672",
                source: "https://www.xeno-canto.org/603672",
                author: "Micha Luhn",
                authorURL: "https://www.xeno-canto.org/contributor/YSPYKACHLO",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },
            {
                id: "XC330973",
                source: "https://www.xeno-canto.org/330973",
                author: "Sylvan Schnabel",
                authorURL: "https://www.xeno-canto.org/contributor/PBXPSXGKLL",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },
            {
                id: "XC263926",
                source: "https://www.xeno-canto.org/263926",
                author: "Terje Kolaas",
                authorURL: "https://www.xeno-canto.org/contributor/CIMGCGUWCS",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },
            {
                id: "XC550608",
                source: "https://www.xeno-canto.org/550608",
                author: "B Whyte",
                authorURL: "https://www.xeno-canto.org/contributor/RWLOMPENJC",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },
            {
                id: "XC224818",
                source: "https://www.xeno-canto.org/224818",
                author: "Peter Boesman",
                authorURL: "https://www.xeno-canto.org/contributor/OOECIWCSWV",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },
            {
                id: "XC381818",
                source: "https://www.xeno-canto.org/381818",
                author: "Uku Paal",
                authorURL: "https://www.xeno-canto.org/contributor/XIBLXHRPJO",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },
        ]
    },
    "goeland_leucophee": {
        identity: {
            commonName: "Goéland leucophée",
            latinName: "Larus michahellis",
            order: "Charadriiformes",
            family: "Laridae",
            genre: "Larus",
        },
        externalSource: [
            {
                id: "XC285382",
                source: "https://www.xeno-canto.org/285382",
                author: "Cedric Mroczko",
                authorURL: "https://www.xeno-canto.org/contributor/TJSRKPHQNP",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },
            {
                id: "XC598877",
                source: "https://www.xeno-canto.org/598877",
                author: "Cedric Mroczko",
                authorURL: "https://www.xeno-canto.org/contributor/TJSRKPHQNP",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },
            {
                id: "XC378210",
                source: "https://www.xeno-canto.org/378210",
                author: "Pascal Christe",
                authorURL: "https://www.xeno-canto.org/contributor/SEIQHUBHAF",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },
            {
                id: "XC566661",
                source: "https://www.xeno-canto.org/566661",
                author: "Marcel Gil Velasco",
                authorURL: "https://www.xeno-canto.org/contributor/METIPYBSWG",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },
            {
                id: "XC460320",
                source: "https://www.xeno-canto.org/460320",
                author: "Nelson Conceição",
                authorURL: "https://www.xeno-canto.org/contributor/JYPQCEFKAM",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },
        ]
    },
    "grand_corbeau": {
        identity: {
            commonName: "Grand corbeau",
            latinName: "Corvus corax",
            order: "Passeriformes",
            family: "Corvidae",
            genre: "Corvus",
        },
        externalSource: [
            {
                id: "XC167827",
                source: "https://www.xeno-canto.org/167827",
                author: "Bodo Sonnenburg",
                authorURL: "https://www.xeno-canto.org/contributor/QAJPWEPSTL",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },
            {
                id: "XC357753",
                source: "https://www.xeno-canto.org/357753",
                author: "Jerome Fischer",
                authorURL: "https://www.xeno-canto.org/contributor/JPBSNBUUEF",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },
            {
                id: "XC72115",
                source: "https://www.xeno-canto.org/72115",
                author: "Richard E. Webster",
                authorURL: "https://www.xeno-canto.org/contributor/KZYUWIRZVH",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },
            {
                id: "XC334273",
                source: "https://www.xeno-canto.org/334273",
                author: "Yoann Blanchon",
                authorURL: "https://www.xeno-canto.org/contributor/OYXLQBTHRH",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },
        ]
    },
    "grive_draine": {
        identity: {
            commonName: "Grive draine",
            latinName: "Turdus viscivorus",
            order: "Passeriformes",
            family: "Turdidae",
            genre: "Turdus",
        },
        externalSource: [
            {
                id: "XC567093",
                source: "https://www.xeno-canto.org/567093",
                author: "Guillaume Bigayon",
                authorURL: "https://www.xeno-canto.org/contributor/HCKTRQCLWR",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },
            {
                id: "XC179931",
                source: "https://www.xeno-canto.org/179931",
                author: "Anthony McGeehan",
                authorURL: "https://www.xeno-canto.org/contributor/TYEQKORVXJ",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },
        ]
    },
    "grive_musicienne": {
        identity: {
            commonName: "Grive musicienne",
            latinName: "Turdus philomelos",
            order: "Passeriformes",
            family: "Turdidae",
            genre: "Turdus",
        },
        externalSource: [
            {
                id: "XC309714",
                source: "https://www.xeno-canto.org/309714",
                author: "Marc Anderson",
                authorURL: "https://www.xeno-canto.org/contributor/EHGWCIGILC",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },
            {
                id: "XC313335",
                source: "https://www.xeno-canto.org/313335",
                author: "Albert Lastukhin",
                authorURL: "https://www.xeno-canto.org/contributor/LELYWQKUZX",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },
            {
                id: "XC213555",
                source: "https://www.xeno-canto.org/213555",
                author: "David Darrell-Lambert",
                authorURL: "https://www.xeno-canto.org/contributor/AYKHDFBYIH",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },
            {
                id: "XC136343",
                source: "https://www.xeno-canto.org/136343",
                author: "Albert Lastukhin",
                authorURL: "https://www.xeno-canto.org/contributor/LELYWQKUZX",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },
        ]
    },
    "merle_noir": {
        identity: {
            commonName: "Merle noir",
            latinName: "Turdus merula",
            order: "Passeriformes",
            family: "Turdidae",
            genre: "Turdus",
        },
        externalSource: [
            {
                id: "XC621418",
                source: "https://www.xeno-canto.org/621418",
                author: "Irish Wildlife Sounds",
                authorURL: "https://www.xeno-canto.org/contributor/PAEQEUHPFQ",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },
            {
                id: "XC329130",
                source: "https://www.xeno-canto.org/329130",
                author: "david m",
                authorURL: "https://www.xeno-canto.org/contributor/BTOFEKXFGW",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },
            {
                id: "XC133825",
                source: "https://www.xeno-canto.org/133825",
                author: "Mike Nelson",
                authorURL: "https://www.xeno-canto.org/contributor/PWDLINYMKL",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },
            {
                id: "XC444376",
                source: "https://www.xeno-canto.org/444376",
                author: "Albert Lastukhin",
                authorURL: "https://www.xeno-canto.org/contributor/LELYWQKUZX",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },
            {
                id: "XC559067",
                source: "https://www.xeno-canto.org/559067",
                author: "Ireneusz Oleksik",
                authorURL: "https://www.xeno-canto.org/contributor/RLRHCUIPIY",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },
        ]
    },
    "mesange_bleue": {
        identity: {
            commonName: "Mésange bleue",
            latinName: "Cyanistes caeruleus",
            order: "Passeriformes",
            family: "Paridae",
            genre: "Cyanistes",
        },
        externalSource: [
            {
                id: "XC218739",
                source: "https://www.xeno-canto.org/218739",
                author: "Anthony McGeehan",
                authorURL: "https://www.xeno-canto.org/contributor/TYEQKORVXJ",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },
            {
                id: "XC626535",
                source: "https://www.xeno-canto.org/626535",
                author: "Stanislas Wroza",
                authorURL: "https://www.xeno-canto.org/contributor/SDPCHKOHRH",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },
            {
                id: "XC278427",
                source: "https://www.xeno-canto.org/278427",
                author: "José Carlos Sires",
                authorURL: "https://www.xeno-canto.org/contributor/DXYUSANLSN",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },
            {
                id: "XC632465",
                source: "https://www.xeno-canto.org/632465",
                author: "Sidney M",
                authorURL: "https://www.xeno-canto.org/contributor/AGCYXCXXSH",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },
            {
                id: "XC204391",
                source: "https://www.xeno-canto.org/204391",
                author: "Mikael Litsgård",
                authorURL: "https://www.xeno-canto.org/contributor/WBXWQVRTFL",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },
            {
                id: "XC528670",
                source: "https://www.xeno-canto.org/528670",
                author: "Tanguy Loïs",
                authorURL: "https://www.xeno-canto.org/contributor/PJVGDPHDIM",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },
        ]
    },
    "mesange_charbonniere": {
        identity: {
            commonName: "Mésange charbonnière",
            latinName: "Parus major",
            order: "Passeriformes",
            family: "Paridae",
            genre: "Parus",
        },
        externalSource: [
            {
                id: "XC638954",
                source: "https://www.xeno-canto.org/638954",
                author: "Marcin Urbański",
                authorURL: "https://www.xeno-canto.org/contributor/FRIYAZCBCA",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },
            {
                id: "XC44965",
                source: "https://www.xeno-canto.org/44965",
                author: "Sander Bot",
                authorURL: "https://www.xeno-canto.org/contributor/HZKCNRIPRH",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },
            {
                id: "XC310273",
                source: "https://www.xeno-canto.org/310273",
                author: "Krzysztof Deoniziak",
                authorURL: "https://www.xeno-canto.org/contributor/VCROLXMVLX",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },
            {
                id: "XC314563",
                source: "https://www.xeno-canto.org/314563",
                author: "iSpiny",
                authorURL: "https://www.xeno-canto.org/contributor/VCWOLAERZN",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },
            {
                id: "XC638756",
                source: "https://www.xeno-canto.org/638756",
                author: "Steve Dettmar",
                authorURL: "https://www.xeno-canto.org/contributor/QTKKZCNHYS",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },
        ]
    },
    "mesange_noire": {
        identity: {
            commonName: "Mésange noire",
            latinName: "Periparus ater",
            order: "Passeriformes",
            family: "Paridae",
            genre: "Periparus",
        },
        externalSource: [
            {
                id: "XC479647",
                source: "https://www.xeno-canto.org/479647",
                author: "François Bouzendorf",
                authorURL: "https://www.xeno-canto.org/contributor/BPZVCQXFLR",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },
            {
                id: "XC385571",
                source: "https://www.xeno-canto.org/385571",
                author: "Antonio Xeira",
                authorURL: "https://www.xeno-canto.org/contributor/PJVICFDZGZ",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },
            {
                id: "XC499274",
                source: "https://www.xeno-canto.org/499274",
                author: "Lars Edenius",
                authorURL: "https://www.xeno-canto.org/contributor/MMEJYLOPDO",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },
            {
                id: "XC255584",
                source: "https://www.xeno-canto.org/255584",
                author: "johannes buhl",
                authorURL: "https://www.xeno-canto.org/contributor/AXTFCLIYDF",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },
            {
                id: "XC189747",
                source: "https://www.xeno-canto.org/189747",
                author: "Sonnenburg",
                authorURL: "https://www.xeno-canto.org/contributor/QAJPWEPSTL",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },
        ]
    },
    "pic_epeiche": {
        identity: {
            commonName: "Pic épeiche",
            latinName: "Dendrocopos major",
            order: "Piciformes",
            family: "Picidae",
            genre: "Dendrocopos",
        },
        externalSource: [
            {
                id: "XC584526",
                source: "https://www.xeno-canto.org/584526",
                author: "johannes buhl",
                authorURL: "https://www.xeno-canto.org/contributor/AXTFCLIYDF",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },
            {
                id: "XC442796",
                source: "https://www.xeno-canto.org/442796",
                author: "W. Agster",
                authorURL: "https://www.xeno-canto.org/contributor/EXNUFPZKKY",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },
            {
                id: "XC169316",
                source: "https://www.xeno-canto.org/169316",
                author: "Jerome Fischer",
                authorURL: "https://www.xeno-canto.org/contributor/JPBSNBUUEF",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },
            {
                id: "XC171739",
                source: "https://www.xeno-canto.org/171739",
                author: "Albert Lastukhin",
                authorURL: "https://www.xeno-canto.org/contributor/LELYWQKUZX",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },
        ]
    },
    "pic_noir": {
        identity: {
            commonName: "Pic noir",
            latinName: "Dryocopus martius",
            order: "Piciformes",
            family: "Picidae",
            genre: "Dryocopus",
        },
        externalSource: [
            {
                id: "XC494794",
                source: "https://www.xeno-canto.org/494794",
                author: "Lars Petter Marthinsen",
                authorURL: "https://www.xeno-canto.org/contributor/WVPAKMSDQV",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },
            {
                id: "XC407246",
                source: "https://www.xeno-canto.org/407246",
                author: "Klaus-Jürgen Papke",
                authorURL: "https://www.xeno-canto.org/contributor/VKTMLABQJH",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },
            {
                id: "XC356924",
                source: "https://www.xeno-canto.org/356924",
                author: "Sonnenburg",
                authorURL: "https://www.xeno-canto.org/contributor/QAJPWEPSTL",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },
        ]
    },
    "pic_vert": {
        identity: {
            commonName: "Pic vert",
            latinName: "Picus viridis",
            order: "Piciformes",
            family: "Picidae",
            genre: "Picus",
        },
        externalSource: [
            {
                id: "XC607970",
                source: "https://www.xeno-canto.org/607970",
                author: "Luca Forneris",
                authorURL: "https://www.xeno-canto.org/contributor/JRCQMEKVKT",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },
            {
                id: "XC237574",
                source: "https://www.xeno-canto.org/237574",
                author: "Frank Holzapfel",
                authorURL: "https://www.xeno-canto.org/contributor/NKZQLCJFUU",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },
            {
                id: "XC498227",
                source: "https://www.xeno-canto.org/498227",
                author: "Frank Pierik",
                authorURL: "https://www.xeno-canto.org/contributor/DFHRMHOGTL",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },
            {
                id: "XC58761",
                source: "https://www.xeno-canto.org/58761",
                author: "Niels Krabbe",
                authorURL: "https://www.xeno-canto.org/contributor/XTVEPHMPPJ",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },
            {
                id: "XC496896",
                source: "https://www.xeno-canto.org/496896",
                author: "Albert Lastukhin",
                authorURL: "https://www.xeno-canto.org/contributor/LELYWQKUZX",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },
        ]
    },
    "pigeon_ramier": {
        identity: {
            commonName: "Pigeon ramier",
            latinName: "Columba palumbus",
            order: "Columbiformes",
            family: "Columbidae",
            genre: "Columba",
        },
        externalSource: [
            {
                id: "XC588876",
                source: "https://www.xeno-canto.org/588876",
                author: "Ad Hilders",
                authorURL: "https://www.xeno-canto.org/contributor/UBDTVCWYPJ",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },
            {
                id: "XC571301",
                source: "https://www.xeno-canto.org/571301",
                author: "Olivier SWIFT",
                authorURL: "https://www.xeno-canto.org/contributor/JCPKCBKKAQ",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },
            {
                id: "XC193888",
                source: "https://www.xeno-canto.org/193888",
                author: "Anthony McGeehan",
                authorURL: "https://www.xeno-canto.org/contributor/TYEQKORVXJ",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },
            {
                id: "XC587346",
                source: "https://www.xeno-canto.org/587346",
                author: "Ad Hilders",
                authorURL: "https://www.xeno-canto.org/contributor/UBDTVCWYPJ",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },
            {
                id: "XC586535",
                source: "https://www.xeno-canto.org/586535",
                author: "Ad Hilders",
                authorURL: "https://www.xeno-canto.org/contributor/UBDTVCWYPJ",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },
        ]
    },
    "pinson_des_arbres": {
        identity: {
            commonName: "Pinson des arbres",
            latinName: "Fringilla coelebs",
            order: "Passeriformes",
            family: "Fringillidae",
            genre: "Fringilla",
        },
        externalSource: [
            {
                id: "XC537811",
                source: "https://www.xeno-canto.org/537811",
                author: "Stanislas Wroza",
                authorURL: "https://www.xeno-canto.org/contributor/SDPCHKOHRH",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },
            {
                id: "XC375997",
                source: "https://www.xeno-canto.org/375997",
                author: "Roby",
                authorURL: "https://www.xeno-canto.org/contributor/KDUPOCIDHM",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },
            {
                id: "XC559760",
                source: "https://www.xeno-canto.org/559760",
                author: "Pierre Foulquier",
                authorURL: "https://www.xeno-canto.org/contributor/YESYDXYEZD",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },
            {
                id: "XC281751",
                source: "https://www.xeno-canto.org/281751",
                author: "Peter Boesman",
                authorURL: "https://www.xeno-canto.org/contributor/OOECIWCSWV",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },
            {
                id: "XC261441",
                source: "https://www.xeno-canto.org/261441",
                author: "Eetu Paljakka",
                authorURL: "https://www.xeno-canto.org/contributor/INCBVJJLBJ",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },
        ]
    },
    "pouillot_veloce": {
        identity: {
            commonName: "Pouillot véloce",
            latinName: "Phylloscopus collybita",
            order: "Passeriformes",
            family: "Phylloscopidae",
            genre: "Phylloscopus",
        },
        externalSource: [
            {
                id: "XC468776",
                source: "https://www.xeno-canto.org/468776",
                author: "Lars Edenius",
                authorURL: "https://www.xeno-canto.org/contributor/MMEJYLOPDO",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },
            {
                id: "XC535498",
                source: "https://www.xeno-canto.org/535498",
                author: "Stanislas Wroza",
                authorURL: "https://www.xeno-canto.org/contributor/SDPCHKOHRH",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },
            {
                id: "XC480519",
                source: "https://www.xeno-canto.org/480519",
                author: "Albert Lastukhin",
                authorURL: "https://www.xeno-canto.org/contributor/LELYWQKUZX",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },
            {
                id: "XC480522",
                source: "https://www.xeno-canto.org/480522",
                author: "Albert Lastukhin",
                authorURL: "https://www.xeno-canto.org/contributor/LELYWQKUZX",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },
            {
                id: "XC480526",
                source: "https://www.xeno-canto.org/480526",
                author: "Albert Lastukhin",
                authorURL: "https://www.xeno-canto.org/contributor/LELYWQKUZX",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },
        ]
    },
    "rougegorge_familier": {
        identity: {
            commonName: "Rouge-gorge familier",
            latinName: "Erithacus rubecula",
            order: "Passeriformes",
            family: "Muscicapidae",
            genre: "Erithacus",
        },
        externalSource: [
            {
                id: "XC617699",
                source: "https://www.xeno-canto.org/617699",
                author: "Michel Barghon",
                authorURL: "https://www.xeno-canto.org/contributor/ZFPMLZXCQV",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },
            {
                id: "XC403639",
                source: "https://www.xeno-canto.org/403639",
                author: "Toon Jansen",
                authorURL: "https://www.xeno-canto.org/contributor/UFBEIQDMLJ",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },
            {
                id: "XC631602",
                source: "https://www.xeno-canto.org/631602",
                author: "Steffen Hartmann",
                authorURL: "https://www.xeno-canto.org/contributor/REYARLBAKR",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },
        ]
    },
    "tourterelle_turque": {
        identity: {
            commonName: "Tourterelle turque",
            latinName: "Streptopelia decaocto",
            order: "Columbiformes",
            family: "Columbidae",
            genre: "Streptopelia",
        },
        externalSource: [
            {
                id: "XC365473",
                source: "https://www.xeno-canto.org/365473",
                author: "Gerard OLIVIER",
                authorURL: "https://www.xeno-canto.org/contributor/QOTYTAAQAK",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },
            {
                id: "XC588868",
                source: "https://www.xeno-canto.org/588868",
                author: "Ad Hilders",
                authorURL: "https://www.xeno-canto.org/contributor/UBDTVCWYPJ",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },
            {
                id: "XC88219",
                source: "https://www.xeno-canto.org/88219",
                author: "Jordi Calvet",
                authorURL: "https://www.xeno-canto.org/contributor/PNYKOPBQBQ",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },
        ]
    },
    "troglodyte_mignon": {
        identity: {
            commonName: "Troglodyte mignon",
            latinName: "Troglodytes troglodytes",
            order: "Passeriformes",
            family: "Troglodytidae",
            genre: "Troglodytes",
        },
        externalSource: [
            {
                id: "XC507551",
                source: "https://www.xeno-canto.org/507551",
                author: "Grzegorz Kaczorowski",
                authorURL: "https://www.xeno-canto.org/contributor/HRHQNZTQAN",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },
            {
                id: "XC534091",
                source: "https://www.xeno-canto.org/534091",
                author: "Sue Riffe",
                authorURL: "https://www.xeno-canto.org/contributor/PVQOLRXXWL",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },
            {
                id: "XC129254",
                source: "https://www.xeno-canto.org/129254",
                author: "Kerem Ali Boyla",
                authorURL: "https://www.xeno-canto.org/contributor/NEMUAOWFZM",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },
            {
                id: "XC555640",
                source: "https://www.xeno-canto.org/555640",
                author: "Harald Knödler",
                authorURL: "https://www.xeno-canto.org/contributor/TLYFJKFXUH",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },
            {
                id: "XC549118",
                source: "https://www.xeno-canto.org/549118",
                author: "Ad Hilders",
                authorURL: "https://www.xeno-canto.org/contributor/UBDTVCWYPJ",
                license: "CC BY-NC-SA 4.0",
                licenseURL: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
            },
        ]
    },
};

export { birds };